### ISSUE TITLE
Trinidad and Tobago

### ISSUE THREAD

**Issue by J0o0** [gdg-wisdom/wisdom-2016#21]
Hi, 

Need some assistance, in regards to starting a GDG chapter, I applied in January 2016 and previously in October 2015, with no response. Found and connected with some one who previously submitted an application and has a GDGTT email and google + page which I now assist in managing. We have had one meetup so far but have not seen our chapter listed on the global directory as incubating. 

Would like to get some assistance on getting the Trinidad and Tobago chapter listed, is there a community manager for the Caribbean Region? 

-label:question

**Comment by friedger** [comment]
I don't think that there is somebody here who can help. I'll forward your message to Adriana.
