### ISSUE TITLE
No response for new GDG chapter since almost 4 months

### ISSUE THREAD

**Issue by princebansal** [gdg-wisdom/wisdom-2016#26]
I have put up a request for a new GDG Chapter in Gwalior, M.P, India. The city is an education hub and has a lot of potential developers. I filled out the form on 23rd June, 2016. But still no response. Please have a look in the issue.

**Comment by friedger** [comment]
Could you please provide a link to the chapter's g+ page?

**Comment by princebansal** [comment]
https://plus.google.com/u/1/106278908907893508178

**Comment by princebansal** [comment]
The chapter hasn't started yet. I think we need a confirmation before starting building. Can you please provide me any missing details?

**Comment by tasomaniac** [comment]
You don't need a confirmation. Confirmation is good because then Google will support you with content, speakers and budget. 
But it is not mandatory. You can just start a meetup local developers around you.

**Comment by friedger** [comment]
The guidelines say so...

Le 20 oct. 2016 13:07, "Said Tahsin Dane" notifications@github.com a
écrit :

**Comment by tasomaniac** [comment]
Does the guidelines say you can start? Or do you need a confirmation? :) I'm confused with your last message

**Comment by nitya** [comment]
Said/Friedger -- there are regional leads from Google and they may be able
to help. Sent you separate email for context if useful.

Prince Bansal -- do you know other GDG orgs in your region? Might be worth
asking if they know who your regional GDG lead is and following up.

**Comment by princebansal** [comment]
The day I sent the request, I got this mail in response from Google:

> Hello,
> Thank you for your Google Developer Group (GDG) support request. If you need to follow up on this request, you can do so by simply replying to this email.
> In most cases, you will hear back from us within one week. However, please allow up to two weeks for someone on the Google Developer Groups Support Team to respond.
> Sincerely,
> The Google Developer Groups Support Team

If I start the chapter without confirmation, how will it be listed in the official GDG directory on google developers website?

**Comment by tasomaniac** [comment]
If you don't get confirmation, of course it will not be listed. And of course being official is better because then you will get official support from regional lead from Google. 
What I was saying that don't wait if it takes too long.

**Comment by princebansal** [comment]
That's what. I need a official registration that will interest others to join as organizers and members. On GDG-Wisdom Gitbook these were the following points listed:

> Ready to start a chapter? Fill out the application form and wait to hear back on the approval of your request. (If you have nothing heard for 2 weeks please open an issue here at gdg-wisdom, your request will then be forwarded to the global Google community manager.)
> Approved? Congratulations!! Check the GDG Directory to verify the chapter listing. It will probably be marked with a  to indicate its incubating status.

It states if not heard within 2 weeks, request will be forwarded to global Google Community manager. What about this?

**Comment by friedger** [comment]
I did that already.

**Comment by princebansal** [comment]
Oh. Than its good. I'll start the formation. Thanks @friedger

**Comment by inesby** [comment]
Hello prince bansal, did you find a solution ?
